import assert from "node:assert/strict";
import test from "node:test";
import { assertExpectedToolCall } from "../src/assertions.ts";
import { starterScenario } from "../src/init.ts";
import { formatJsonReport } from "../src/reportJson.ts";
import { parseScenario } from "../src/scenario.ts";

test("parses the explicit v0 scenario shape", () => {
  const scenario = parseScenario(`
id: refund_request
agent: support

locales:
  en:
    input: "I was charged twice."
    expect:
      toolCall:
        name: create_refund_ticket
        arguments:
          reason: duplicate_charge
      noToolCall:
        name: escalate_to_human
`);

  assert.equal(scenario.id, "refund_request");
  assert.equal(scenario.agent, "support");
  assert.equal(scenario.locales.en.input, "I was charged twice.");
  assert.equal(scenario.locales.en.expect.toolCall.name, "create_refund_ticket");
  assert.deepEqual(scenario.locales.en.expect.toolCall.arguments, {
    reason: "duplicate_charge",
  });
  assert.equal(scenario.locales.en.expect.noToolCall?.name, "escalate_to_human");
});

test("fails when the expected tool call is missing", () => {
  const result = assertExpectedToolCall(
    { toolCall: { name: "create_refund_ticket" } },
    { text: "I can help.", toolCalls: [], structured: null },
  );

  assert.deepEqual(result, {
    pass: false,
    failureMode: "no_tool_call",
    detail: "expected create_refund_ticket, got no tool calls",
  });
});

test("fails when an expected tool call argument is missing", () => {
  const result = assertExpectedToolCall(
    {
      toolCall: {
        name: "create_refund_ticket",
        arguments: { reason: "duplicate_charge" },
      },
    },
    {
      text: "I can help.",
      toolCalls: [{ name: "create_refund_ticket", arguments: {} }],
      structured: null,
    },
  );

  assert.deepEqual(result, {
    pass: false,
    failureMode: "missing_argument",
    detail: "expected argument reason=duplicate_charge, got missing",
  });
});

test("fails when a forbidden tool call appears", () => {
  const result = assertExpectedToolCall(
    {
      toolCall: { name: "create_refund_ticket" },
      noToolCall: { name: "escalate_to_human" },
    },
    {
      text: "I need a person.",
      toolCalls: [{ name: "create_refund_ticket" }, { name: "escalate_to_human" }],
      structured: null,
    },
  );

  assert.deepEqual(result, {
    pass: false,
    failureMode: "forbidden_tool",
    detail: "forbidden tool call escalate_to_human was called",
  });
});

test("passes when a forbidden tool call is absent", () => {
  const result = assertExpectedToolCall(
    {
      toolCall: { name: "create_refund_ticket" },
      noToolCall: { name: "escalate_to_human" },
    },
    {
      text: "I can help.",
      toolCalls: [{ name: "create_refund_ticket" }],
      structured: null,
    },
  );

  assert.deepEqual(result, {
    pass: true,
    failureMode: null,
    detail: "create_refund_ticket",
  });
});

test("fails when an expected tool call argument has the wrong value", () => {
  const result = assertExpectedToolCall(
    {
      toolCall: {
        name: "create_refund_ticket",
        arguments: { reason: "duplicate_charge" },
      },
    },
    {
      text: "I can help.",
      toolCalls: [{ name: "create_refund_ticket", arguments: { reason: "other" } }],
      structured: null,
    },
  );

  assert.deepEqual(result, {
    pass: false,
    failureMode: "wrong_argument",
    detail: "expected argument reason=duplicate_charge, got other",
  });
});

test("passes when expected tool call arguments match", () => {
  const result = assertExpectedToolCall(
    {
      toolCall: {
        name: "create_refund_ticket",
        arguments: { reason: "duplicate_charge" },
      },
    },
    {
      text: "I can help.",
      toolCalls: [
        {
          name: "create_refund_ticket",
          arguments: { reason: "duplicate_charge", locale: "en" },
        },
      ],
      structured: null,
    },
  );

  assert.deepEqual(result, {
    pass: true,
    failureMode: null,
    detail: "create_refund_ticket",
  });
});

test("passes when the expected tool call appears", () => {
  const result = assertExpectedToolCall(
    { toolCall: { name: "create_refund_ticket" } },
    {
      text: "I can help.",
      toolCalls: [{ name: "create_refund_ticket" }],
      structured: null,
    },
  );

  assert.deepEqual(result, {
    pass: true,
    failureMode: null,
    detail: "create_refund_ticket",
  });
});

test("starter scenario generated by init is parseable", () => {
  const scenario = parseScenario(starterScenario());

  assert.equal(scenario.id, "refund_request");
  assert.equal(scenario.agent, "support");
  assert.deepEqual(Object.keys(scenario.locales), ["en", "fr"]);
  assert.equal(scenario.locales.en.expect.toolCall.name, "create_refund_ticket");
});

test("formats a stable JSON run report", () => {
  const report = formatJsonReport({
    scenarioId: "refund_request",
    target: "http://127.0.0.1:3010/api/agent",
    results: [
      {
        locale: "en",
        status: "pass",
        failureMode: null,
        detail: "create_refund_ticket",
      },
      {
        locale: "fr",
        status: "fail",
        failureMode: "no_tool_call",
        detail: "expected create_refund_ticket, got no tool calls",
      },
    ],
  });

  const parsed = JSON.parse(report) as {
    schemaVersion: number;
    status: string;
    summary: { total: number; passed: number; failed: number };
    results: Array<{ locale: string; status: string }>;
  };

  assert.equal(parsed.schemaVersion, 1);
  assert.equal(parsed.status, "failed");
  assert.deepEqual(parsed.summary, { total: 2, passed: 1, failed: 1 });
  assert.deepEqual(
    parsed.results.map((result) => [result.locale, result.status]),
    [
      ["en", "pass"],
      ["fr", "fail"],
    ],
  );
});
